language: node_js
node_js:
  - "7"
services:
  - mongodb
after_script:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN node node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info